name: Build an iso

on:
  workflow_call:
    inputs: &inputs
      variant:
        description: Which variant to generate an ISO for
        type: string
        required: true
      pull:
        description: Pull the latest image, or use the workflow artifact
        type: boolean
        default: false
        required: false
      artifact:
        description: Artifact to load base image from
        type: string
        required: false
        default: ""
      digest:
        description: Digest to expect base image to be
        type: string
        required: false
        default: ""
      push:
        # TODO implement this
        description: Push the generated iso
        type: boolean
        default: false
        required: false
      builder:
        description: Builder tag to use
        required: false
        type: string
  workflow_dispatch:
    inputs: *inputs

permissions:
  contents: write
  packages: read

jobs:
  run:
    name: arkes:${{ inputs.variant }} iso
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eeems/arkes-builder:${{ inputs.builder || github.head_ref || github.ref_name }}
      options: >-
        --privileged
        --security-opt=seccomp=unconfined
        --security-opt=apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device=/dev/fuse
        --tmpfs=/tmp
        --tmpfs=/run
        --userns=host
        --volume=/:/run/host
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup container
        uses: ./.github/actions/setup-container

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Free up space
        uses: ./.github/actions/cleanup
        with:
          root: /run/host

      - name: Import image
        if: inputs.artifact != ''
        uses: ./.github/actions/import-container
        with:
          artifact: ${{ inputs.artifact }}
          image: ghcr.io/eeems/arkes:${{ inputs.artifact }}

      - name: Get manifest cache
        if: inputs.artifact != ''
        uses: ./.github/actions/manifest-cache-restore
        with:
          key: manifest_${{ inputs.artifact }}
          artifact: true

      - name: Pacman cache
        uses: actions/cache/restore@v4
        with:
          key: pacman-iso-${{ inputs.variant }}-${{ github.head_ref || github.ref_name }}
          path: /var/cache/pacman

      - name: Force digest
        if: inputs.digest != '' && inputs.artifact != ''
        uses: ./.github/actions/force-image-digest
        with:
          tag: ${{ inputs.artifact }}
          digest: ${{ inputs.digest }}

      - name: Build
        uses: ./.github/actions/run-with-podman-service
        with:
          run: ./make.py iso ${{ inputs.variant }}

      - name: Pacman cache
        uses: ./.github/actions/pacman-cache-update
        with:
          key: pacman-iso-${{ inputs.variant }}-${{ github.head_ref || github.ref_name }}

      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          name: arkes-${{ inputs.variant }}.iso
          path: /var/lib/system/arkes-${{ inputs.variant }}-*.iso

      - name: Move iso
        run: mv /var/lib/system/arkes-${{ inputs.variant }}-*.iso .

      - name: Update release
        uses: ading2210/gh-large-releases@v1
        if: inputs.push
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: arkes-${{ inputs.variant }}-*.iso
          name: ${{ inputs.variant }}
          body: ${{ inputs.variant }} variant
          tag_name: variant/${{ inputs.variant }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: false
          draft: false
          prerelease: true

      - name: Update latest release
        if: inputs.push
        shell: bash
        run: |
          set -e
          if ! gh release view latest >/dev/null;then
            gh release create latest \
              --title "Latest" \
              --prerelease
          fi

          truncate --size 0 /tmp/body.txt
          echo "| File Name | Size | SHA-256 Hash |" > /tmp/body.txt
          echo "| --------- | ---- | ------------ |" >> /tmp/body.txt
          while read -r variant;do
            if ! gh release view "$variant" >/dev/null 2>&1;then
              continue
            fi
            gh release view "$variant" --json body \
            | jq -r '.body' \
            | awk '/START_BIG_ASSET_LIST_DO_NOT_REMOVE/{flag=1;next} /END_BIG_ASSET_LIST_DO_NOT_REMOVE/{flag=0} flag' \
            | grep -E '^\|.*\|$' \
            | awk 'NR>2' >> /tmp/body.txt
          done < <(./make.py variants)

          git tag -f latest "${{ github.sha }}"
          git push -f origin refs/tags/latest
          gh release edit latest \
            --title "Latest" \
            --tag latest \
            --target "${{ github.sha }}" \
            --notes-file /tmp/body.txt \
            --latest \
            --draft=false

          git tag -f "variant/${{ inputs.variant }}" "${{ github.sha }}"
          git push -f origin "refs/tags/variant/${{ inputs.variant }}"
          gh release edit "variant/${{ inputs.variant }}" --draft=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
