name: Build builder image
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      unique_tag:
        value: ${{ jobs.builder.outputs.unique_tag }}

permissions:
  contents: read
  packages: write

jobs:
  builder:
    runs-on: ubuntu-latest
    outputs:
      unique_tag: ${{ steps.meta.outputs.unique_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - uses: ./.github/actions/mask-registry-passwords

      - name: Generate tags
        id: meta
        run: |
          IMAGE_NAME=ghcr.io/eeems/arkes-builder
          HASH="$(python ./make/hash-builder.py --no-newline)"
          echo "unique_tag=${HASH}" >> $GITHUB_OUTPUT
          echo "image=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tags=${IMAGE_NAME}:${{ github.head_ref || github.ref_name }},${IMAGE_NAME}:${HASH}" >> $GITHUB_OUTPUT
          echo "missing=$(skopeo list-tags docker://ghcr.io/eeems/arkes-builder | jq 'any(.Tags[]; . == "${HASH}") | not')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Build and push
        if: fromJson(steps.meta.outputs.missing)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: tools/builder/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
